{"kind":"symbol","identifier":{"url":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge\/getStatus()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getStatus","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"EdgeEngine"}],"externalID":"c:objc(cs)Edge(im)getStatus","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getStatus","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"role":"symbol","symbolKind":"method","title":"getStatus()","navigatorTitle":[{"kind":"identifier","text":"getStatus"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine","doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge"]]},"variants":[{"paths":["\/documentation\/edgeengine\/edge\/getstatus()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/edgeengine\/edge\/getstatus()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.mimik.cocoapod.EdgeEngine/documentation/EdgeEngine":{"kind":"symbol","identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine","role":"collection","abstract":[{"type":"text","text":"mimik Client Library provides a programmatic way to work with the edgeEngine Runtime to access information about the mobile device on which the application is running."}],"title":"EdgeEngine","url":"\/documentation\/edgeengine","type":"topic"},"doc://com.mimik.cocoapod.EdgeEngine/documentation/EdgeEngine/Edge":{"identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge","navigatorTitle":[{"text":"Edge","kind":"identifier"}],"url":"\/documentation\/edgeengine\/edge","type":"topic","abstract":[],"title":"Edge","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Edge"}],"kind":"symbol"},"doc://com.mimik.cocoapod.EdgeEngine/documentation/EdgeEngine/Edge/getStatus()":{"identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge\/getStatus()","navigatorTitle":[{"kind":"identifier","text":"getStatus"}],"abstract":[],"type":"topic","url":"\/documentation\/edgeengine\/edge\/getstatus()","title":"getStatus()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getStatus","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"getStatus"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getStatus"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"int","preciseIdentifier":"c:I","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"getStatus"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge\/title","value":"Edge"},{"path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge\/fragments","value":[{"text":"Edge","kind":"identifier"}],"op":"replace"},{"value":"getStatus","op":"replace","path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge~1getStatus()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge~1getStatus()\/fragments"}]}]}