{"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"stop"}],"modules":[{"name":"EdgeEngine"}],"title":"stop()","externalID":"c:objc(cs)Edge(im)stop","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/edgeengine\/edge\/stop()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/edgeengine\/edge\/stop()"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine","doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge\/stop()"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"style":"note","type":"aside","name":"Note","content":[{"inlineContent":[{"type":"text","text":"For more information about the edgeEngine platform see mimik "},{"identifier":"https:\/\/devdocs.mimik.com\/introduction","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Developers ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"should not use this method directly"}]},{"type":"text","text":", and instead should use the available "},{"type":"codeVoice","code":"EdgeCore"},{"text":" client library ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/mimikgit.github.io\/cocoapod-EdgeCore\/documentation\/edgecore"}]}],"type":"aside","style":"warning","name":"Warning"}]}],"sections":[],"abstract":[{"type":"text","text":"Private declaration of a method stopping the "},{"type":"codeVoice","code":"edgeEngine"},{"type":"text","text":" instance. "},{"type":"strong","inlineContent":[{"text":"For internal mimik use.","type":"text"}]}],"references":{"doc://com.mimik.cocoapod.EdgeEngine/documentation/EdgeEngine/Edge/stop()":{"type":"topic","navigatorTitle":[{"text":"stop","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/edgeengine\/edge\/stop()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stop"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge\/stop()","abstract":[{"type":"text","text":"Private declaration of a method stopping the "},{"code":"edgeEngine","type":"codeVoice"},{"type":"text","text":" instance. "},{"type":"strong","inlineContent":[{"text":"For internal mimik use.","type":"text"}]}],"role":"symbol","title":"stop()"},"https://mimikgit.github.io/cocoapod-EdgeCore/documentation/edgecore":{"title":"API","type":"link","identifier":"https:\/\/mimikgit.github.io\/cocoapod-EdgeCore\/documentation\/edgecore","titleInlineContent":[{"text":"API","type":"text"}],"url":"https:\/\/mimikgit.github.io\/cocoapod-EdgeCore\/documentation\/edgecore"},"doc://com.mimik.cocoapod.EdgeEngine/documentation/EdgeEngine/Edge":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Edge","kind":"identifier"}],"navigatorTitle":[{"text":"Edge","kind":"identifier"}],"abstract":[{"type":"text","text":"Private declaration of "},{"type":"codeVoice","code":"edgeEngine"},{"type":"text","text":" platform class. "},{"inlineContent":[{"text":"For internal mimik use.","type":"text"}],"type":"strong"}],"role":"symbol","title":"Edge","identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge","kind":"symbol","url":"\/documentation\/edgeengine\/edge"},"https://devdocs.mimik.com/introduction":{"type":"link","identifier":"https:\/\/devdocs.mimik.com\/introduction","url":"https:\/\/devdocs.mimik.com\/introduction","title":"DevDocs","titleInlineContent":[{"text":"DevDocs","type":"text"}]},"doc://com.mimik.cocoapod.EdgeEngine/documentation/EdgeEngine":{"role":"collection","url":"\/documentation\/edgeengine","type":"topic","abstract":[{"text":"mimik Client Library provides a programmatic way to work with the edgeEngine Runtime to access information about the mobile device on which the application is running.","type":"text"}],"title":"EdgeEngine","kind":"symbol","identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"stop","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stop"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge~1stop()\/title","value":"stop"},{"path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge~1stop()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"stop","kind":"identifier"}],"op":"replace"},{"value":"Edge","path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge\/title","op":"replace"},{"value":[{"text":"Edge","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge\/fragments"}]}]}